# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13zOKkeOG9oIp4JlGY5Ph8Rx7ubXQmP5U
"""

! sudo apt install tesseract-ocr 
! pip install pytesseract
! sudo apt-get install tesseract-ocr-por
! sudo apt-get install tesseract-ocr-por

import pytesseract
import shutil
import os
import random
try:
 from PIL import Image
except ImportError:
 import Image

import numpy as np
import pandas as pd
import cv2 as cv 
from google.colab.patches import cv2_imshow # for image display
from skimage import io
from PIL import Image 
import matplotlib.pylab as plt
import scipy

urls = ["pozemau.jpg"]

for url in urls:
  image = cv.imread(url) 
  gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
  graySpace = cv.cvtColor(gray,cv.COLOR_GRAY2BGR)

  final_frame = np.hstack((image, graySpace))

  cv2_imshow(final_frame)

face_cascade = cv.CascadeClassifier('haarcascade_frontalface_default.xml')


faces = face_cascade.detectMultiScale(image,scaleFactor = 1.05, minNeighbors = 7, minSize = (30,30), flags = cv.CASCADE_SCALE_IMAGE)


for (x,y,w,h) in faces:
     cv.rectangle(image,(x,y),(x+w,y+h),(0,0,255),2)

cv2_imshow(image)

urls2 = ["pozefrases.jpg"]

# Ler e mostra cada imagem da lista em BGR e RGB:
for url in urls2:
  image = cv.imread(url) 
  image_2 = cv.cvtColor(image, cv.COLOR_BGR2RGB)
  
  final_frame = cv.hconcat((image, image_2)) 
  cv2_imshow(final_frame)

extractedInformation = pytesseract.image_to_string(image, lang='por')
print(extractedInformation)